version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=Ob31EpHOqbqEt2IE
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:25060'
volumes:
  postgres: